# -*- coding: utf-8 -*-
"""DEA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R31OWpcbTLx2SqBaNaONoHZaN70mVYg5
"""

import pandas as pd
import random

import pandas as pd
import random

# Load the "amir.xlsx" file into a pandas DataFrame
amir_df = pd.read_excel("amir.xlsx")

# Load the "random numbers.xlsx" file into a pandas DataFrame
random_numbers_df = pd.read_excel("random numbers.xlsx")

# Iterate through the random DMU numbers
for dmu_number in random_numbers_df['DMU Number']:
    # Check if the DMU number exists in the "amir.xlsx" DataFrame
    if dmu_number in amir_df['DMU Number'].values:
        # Find the index of the row with the matching DMU number
        index = amir_df.index[amir_df['DMU Number'] == dmu_number].tolist()[0]

        # Generate a random choice of -5 or 5 for the percentage change
        percentage_change = random.choice([-5, 5])

        # Iterate through columns B to I and apply the same percentage change
        for col in ['Input 1', 'Input 2', 'Input 3', 'Input 4', 'Input 5', 'Input 6', 'Input 7', 'Output']:
            current_value = amir_df.at[index, col]

            # Calculate the new value with the same percentage change
            new_value = current_value * (1 + (percentage_change / 100))

            # Update the DataFrame with the new value
            amir_df.at[index, col] = new_value

# Save the modified DataFrame to a new Excel file
amir_df.to_excel("amir_modified.xlsx", index=False)

import pandas as pd

# Load the Excel file into a DataFrame
file_path = '1.xlsx'
df = pd.read_excel(file_path)

# Specify the column name that contains the data
column_name = '1'  # Replace 'YourColumnName' with the actual column name

# Remove '-' characters from the specified column
df[1] = df[1].str.replace('-', '')

# Save the modified DataFrame back to the Excel file
df.to_excel(file_path, index=False)

# Print the first few rows of the modified DataFrame
print(df.head())
